apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: proshop
  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: my-backend-app:v1   
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000

        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: NODE_ENV

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT

        - name: PAYPAL_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PAYPAL_CLIENT_ID

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_URI

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
